#!/bin/bash
IMG=$(cat IMAGE)
DOCKERHOME=$(pwd)/.dockerhome
PACKAGE_ROOT=$(pwd)/packages
OPT=${OPT:-""}
docker run \
    -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) \
    -e HOME=${DOCKERHOME} -v ${DOCKERHOME}:${DOCKERHOME} \
    --rm --init -it -e PYTHONPATH=${PACKAGE_ROOT} \
    ${OPT} ${IMG} "$@"
